# Generated by Django 4.1.5 on 2023-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dl/upload_files/')),
                ('file_name', models.CharField(max_length=100, verbose_name='ダウンロード時に使うファイル名')),
            ],
        ),
    ]
