# Generated by Django 4.1.6 on 2023-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_uploadfile_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='serial_number',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='製造番号'),
        ),
    ]
