# Generated by Django 4.1.6 on 2023-02-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_alter_uploadfile_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
