# Generated by Django 4.1.6 on 2023-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
