# Generated by Django 4.1.6 on 2023-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0005_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ダウンロード時に使うファイル名'),
        ),
    ]
